### ISSUE TITLE
Fix annoying Texture() bug

### ISSUE THREAD

**Issue by Furthen64** [Furthen64/hurkalumo#24]
**Symptom:**
```
An internal OpenGL call failed in Texture.cpp(98).
Expression:
   glFlush()
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.
```
**Recreate:**
Create any sf::Texture object in Debug mode in Code::Blocks within HurkaLumo project (2018-06),
and create the texture before you have an OpenGL handle . The handle is an open sf::RenderWindow.

**Solution:**
Fix them by never allocating sf::Texture objects without having a sf::RenderWindow created in the same scope

- [x] Figure out a better design
- [x] Implement one
- [x] Regression test functions

**Comment by Furthen64** [comment]
Seems to work fine, albeit that extra window is not a nice design. Alpha-0.2 issue added!

**Comment by mohprohack** [comment]
Thank you very much, it worked very well
